sample-$(AIO_SAMPLES) += aio-reader
sample-aio-reader-$(AIO_SAMPLES) := aio-reader.c

sample-$(GPIO_SAMPLES) += gpio-reader gpio-writer
sample-gpio-reader-$(GPIO_SAMPLES) := gpio-reader.c
sample-gpio-writer-$(GPIO_SAMPLES) := gpio-writer.c

sample-$(PWM_SAMPLES) += pwm
sample-pwm-$(PWM_SAMPLES) := pwm.c
