sample-$(AIO_SAMPLES) += aio-reader
sample-aio-reader-$(AIO_SAMPLES) := aio-reader.c

sample-$(GPIO_SAMPLES) += gpio-reader gpio-writer
sample-gpio-reader-$(GPIO_SAMPLES) := gpio-reader.c
sample-gpio-writer-$(GPIO_SAMPLES) := gpio-writer.c

sample-$(PWM_SAMPLES) += pwm
sample-pwm-$(PWM_SAMPLES) := pwm.c

sample-$(SPI_SAMPLES) += spi
sample-spi-$(SPI_SAMPLES) := spi.c

sample-$(UART_SAMPLES) += uart
sample-uart-$(UART_SAMPLES) := uart.c
